### ISSUE TITLE
Make WoolyWoolly drawable canvas extend to be the maximum browser width.

### ISSUE THREAD

**Issue by ericheep** [proud-dogs/sand#2]
Currently the canvas does not scale with the browser width, I think we might want it to extend across the whole window?

<img width="1203" alt="screen shot 2017-11-26 at 2 46 16 pm" src="https://user-images.githubusercontent.com/6289030/33245160-9dab0f60-d2b8-11e7-812d-1451d5b75586.png">

**Comment by clarkenciel** [comment]
this will be fun. we'll probably need a new piece of UI state here to track browser width while resizing
